
language: java
os: linux
dist: bionic
arch: amd64
jdk:
  - openjdk11
cache:
  bundler: false
  cargo: false
  directories:
    - '$HOME/.m2'

addons:
  sonarcloud:
    organization: "valentino7"
    token: 16c60fb810abad347b7fe8242f05a1f40b09a71d
git:
  depth: 2
env:
  global:
  - MAVEN_OPTS="-Xmx4096M -Xss128M -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -noverify"
  - JAVAEE_CONTAINER=Tomcat
  - DBMS=H2
  - jaxrsContentType=application/json

before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh -O ~/install-jdk.sh && chmod +x ~/install-jdk.sh
script: mvn -U -T 1C clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=valentino7_syncope -Dinvoker.streamLogs=true -Dmodernizer.skip=true -Dianal.skip=true -Drat.skip=true -Dcheckstyle.skip=true -Dsass.skip=true
